#page title
page_title                                :  Italy Nowadays                                         # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# App Info
ios_app_id                                : 1581280209                                # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).
ios_app_country                           : it                                        # Required outside USA. Enter 2 letter country code as in https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2

appstore_link                             :   https://apps.apple.com/it/app/italy-nowadays/id1581280209                                        # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link                            :   https://play.google.com/store/apps/details?id=com.dariopellegrini.italynowadays     # Enter Google Play Store URL.
presskit_download_link                    :                                       # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file). 
                                                                                      # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon                                  : assets/appicon.png                      # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name                                  : Italy Nowadays                                          # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price                                 : Free                                         # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description                           : News dall'Italia, aggiornate, veloci, sicure

enable_smart_app_banner                   : true                                      # Set to true to show a smart app banner at top of page on mobile devices.



# Information About Yourself
your_name                                 : Italy Nowadays                           
your_link                                 : https://app.italynowadays.it                  
your_city                                 : Brescia                                
email_address                             : italynowadays@gmail.com
facebook_username                         :                                           
instagram_username                        : 
twitter_username                          : 
github_username                           : 
youtube_username                          :



# Feature List                            Edit, add or remove features to be presented.
features                                  :

  - title                                 : News dall'Italia sempre aggiornate
    description                           : Le nostre news vengono recuperate da <a href="https://www.ansa.it/sito/static/ansa_rss.html">RSS ANSA</a> e sono sempre aggiornate e corrette, di ora in ora.
    fontawesome_icon_name                 : newspaper
    
  - title                                 : Video news giornaliere
    description                           : Grazie a <a href="https://www.ansa.it/sito/static/ansa_rss.html">RSS ANSA</a> offriamo video giornalieri sulle notizie più interessanti d'Italia.
    fontawesome_icon_name                 : rss

  - title                                 : Ricerca veloce
    description                           : Integriamo una ricerca veloce tra le nostre news e i nostri video, dando così una visione sempre precisa e accurata.
    fontawesome_icon_name                 : compass

  - title                                 : Dati ANSA
    description                           : L'utilizzo di <a href="https://www.ansa.it/sito/static/ansa_rss.html">RSS ANSA</a> ci permette di proporre le migliori news d'Italia in modo tempestivo e sintetico.
    fontawesome_icon_name                 : database

  - title                                 : Gratis e senza pubblicità
    description                           : Italy Nowadays è un'app realizzata senza scopo di lucro e ha come unico fine offrire a tutti news sicure e veloci, senza costi aggiuntivi o pubblicità e senza tracciare nessun dato dell'utente.
    fontawesome_icon_name                 : gift
  
  - title                                 : Contattaci
    description                           : Per qualsiasi informazione in merito a Italy Nowadays contattaci <a href="mailto:italynowadays@gmail.com">via e-mail</a>.
    fontawesome_icon_name                 : envelope
    

# Theme Settings
topbar_color                              : "#000000"
topbar_transparency                       : 0.1
topbar_title_color                        : "#ffffff"

cover_image                               : assets/world.jpg                 # Replace with alternative image path or image URL.
cover_overlay_color                       : "#363b3d"
cover_overlay_transparency                : 0.8

device_color                              : black                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "#ffffff"

link_color                                : "#000000"

app_title_color                           : "#ffffff"
app_price_color                           : "#ffffff"
app_description_color                     : "#ffffff"

feature_title_color                       : "#000000"
feature_text_color                        : "#666666"

feature_icons_foreground_color            : "#000000"
feature_icons_background_color            : "#e6e6e6"

social_icons_foreground_color             : "#666666"
social_icons_background_color             : "#e6e6e6"

footer_text_color                         : "#666666"













####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown
